### ISSUE TITLE
一个star都不值的东西 , 自己刷有意思?

### ISSUE THREAD

**Issue by lyonyang** [herry-zhang/Python3-RESTfulAPI#5]
删我Issues , 你写的这个东西如果真的有一点用处 , 我没话说 , 看你写的东西估计你不是做后端的 . 麻烦你好好看看你写的东西再放上来 , 别误人子弟 ~

**Comment by herry-zhang** [comment]
开头已经说明了如果你觉着有问题可以提出来，我们可以一起交流，另外你是从哪里得出来的结论，我是刷star，哪里可以刷49个star，你除了当喷子能不能提出点有意义的东西

**Comment by lyonyang** [comment]
第一 , 你好好看看你的requirements.txt
第二 , 设计表长度是否合理
第三 , 你这就是一个hello world , desc写得这么全有什么用
我不喷人 , 我只是看不惯既然是技术交流 , 那么前提你应该保证 , 你写的东西不应该存在大问题 , 或者 , 你应该写点真正有意义的东西 , 比如你这个 , 官方文档写的那么好 , 何必自己写个连官方hello world 都不如的东西?
